#!/bin/bash

if [ -z "$1" ]; then 
    echo usage: $0 DATABASE; exit;
fi

root='mysqldump_'$1
folder=`date '+%Y%m%d-%H%M%S'`
if [ ! -d $root ]; then
    mkdir $root
fi
mkdir $root/$folder

cd $root/$folder

for i in $( mysql -D $1 -e "SHOW TABLES;" | sed '1d' ); do
    echo "table: " $i
    mysql_d3dump_schema $1 $i
    mysql_d3dump_data $1 $i
done

mysql_d3dump_solid $1
cd ../..

