#!/bin/bash

# ==========================
# Import functions
source `which mysql_d3_librc`

avaliable_commands_list='help data schema solid all truncate truncatetable truncatedb'
function usage {
    echo ''
    echo 'Modify data in database'
    echo 'Import data from database__table--type.sql file , wo output'
    echo ''
    echo usage:
    echo '    '$cmd help;
    echo '    '$cmd all\|solid DATABASE;
    echo '    '$cmd data\|schema DATABASE [TABLE];
    echo example:
    echo '    '$cmd data mysql Users
    echo '    '$cmd schema mysql Users
    echo '    '$cmd truncate wpb
    echo
}

checkout_command $@
oldpwd=`pwd`;

if test $1 == 'help'; then
    usage;
    exit;
fi

if test $1 == 'solid'; then
    checkout_database $@
    checkout_folder $@
    # sqlfile=$( ls -1 *.sql | grep -e '--solid.sql' | head -n 1 );
    cd $3;
    sqlfile=$2--solid.sql;
    if [ -f $sqlfile ]; then
        echo injecting $sqlfile ...;
        $cmd_mysql -D $2 < $sqlfile;
    else
        echo error: $3/$sqlfile not found;
    fi
    cd $oldpwd;
    exit;
fi

if test $1 == 'all'; then
    # mysqlimport
    checkout_database $@
    checkout_folder $@
    cd $3;
    mysql_d3restore drop $2;
    echo;
    for f in $( ls -1 $2__*--schema.sql ); do
        f=${f%--schema.sql};
        f=${f#$2__};
        mysql_d3restore schema $2 $f;
    done
    echo;
    for f in $( ls -1 $2__*--data.sql ); do
        f=${f%--data.sql};
        f=${f#$2__};
        mysql_d3restore data $2 $f;
    done
    echo;
    mysql_d3info structure $2 | column -t;
    mysql_d3info structure $2 | column -t > structure.txt;
    cd $oldpwd;
    exit;
fi

if test $1 == 'data'; then
    checkout_database $@
    checkout_table $@
    sqlfile=$2__$3--data.sql;
    if [ -f $sqlfile ]; then
        echo injecting $sqlfile ...;
        $cmd_mysql -D $2 < $sqlfile;
    else
        echo error: $sqlfile not found;
    fi
    exit;
fi

if test $1 == 'schema'; then
    checkout_database $@
    checkout_table $@
    sqlfile=$2__$3--schema.sql;
    if [ -f $sqlfile ]; then
        echo injecting $sqlfile ...;
        $cmd_mysql -D $2 < $sqlfile;
    else
        echo error: $sqlfile not found;
    fi
    exit;
fi

if test $1 == 'truncate'; then
    checkout_database $@
    for TABLE in $( mysql_lambda_query $2 "SHOW TABLES" ); do
        mysql_lambda_query $2 "TRUNCATE $TABLE";
    done
    echo All TABLES were truncated
    exit;
fi

if test $1 == 'truncatetable'; then
    echo todo : join with truncate
    exit;
    # DEPRECATED
    checkout_database $@
    checkout_table $@
    mysql_lambda_query $2 "TRUNCATE $3";
    echo TABLE $3 was truncated
    exit;
fi

if test $1 == 'drop'; then
    checkout_database $@
    for TABLE in $( mysql_lambda_query $2 "SHOW TABLES" ); do
        mysql_lambda_query $2 "DROP TABLE IF EXISTS $TABLE";
    done
    echo All tables droped
    # mysql -D $1 -e "TRUNCATE $DATABASE";
    exit;
fi

not_recognized $1
