#!/bin/bash

cmd=`basename $0`

# cmd pseudo-aliases cause of environment alias incapacity
if [ -z $mysql_group_suffix ]; then
    # echo could not extend mysqldump :  \$mysql_group_suffix is null;
    cmd_mysql="mysql";
    cmd_dump="mysqldump --compact";
else
    cmd_mysql="mysql --defaults-group-suffix=$mysql_group_suffix";
    cmd_dump="mysqldump --defaults-group-suffix=$mysql_group_suffix --compact";
    # mysqldump flags
    # --skip-opt
    # --compact
fi

function mysql_lambda_query {
    $cmd_mysql -D $1 -e "$2;" | sed '1d';
    # echo $cmd_mysql -D $1 -e "$2;";
}
function to_mysqldb_query {
    $cmd_mysql -D 'mysql' -e "$1";
}

function avaliable {
    echo "Avaliable commands : $avaliable_commands_list";
    echo;
}
function show_help {
    if [ "$1" == 'help' ]; then
        usage;
        exit;
    fi
}

function checkout_connection {
    $cmd_mysql -e '\c';
    connection_code=$?;
    # if [ $? -eq 0 ]; then
        # connection_code=0;
    # else
        # connection_code=2;
    # fi
    if [ -z "$1" ]; then
        # silent mode
        if [ $connection_code -ne 0 ]; then
            exit;
        fi
    else
        # print mode
        if test $1 == 'out'; then
            if [ $connection_code -ne 0 ]; then
                # echo "no connection to DB:" $2;
                echo 'Connection : Fails';
            else
                echo 'Connection : OK';
            fi
            return;
        else
            echo 'unknown cmd';
        fi
        exit;
    fi
    # connection_code=$?;
}

function checkout_command {
    if [ -z "$1" ]; then
        avaliable;
        exit;
    fi
}
function checkout_database {
    if [ -z "$2" ]; then
        echo 'specify database:';
        echo '    '$cmd $1 DATABASE;
        echo;
        exit;
    fi
}
function checkout_name {
    if [ -z "$2" ]; then
        echo 'specify name:';
        echo '    '$cmd $1 NAME;
        echo;
        exit;
    fi
}
function checkout_folder {
    if [ -z "$3" ]; then
        echo 'specify folder:';
        echo '    '$cmd $1 $2 FOLDER;
        echo;
        exit;
    else
        if [ -d $3 ]; then
            echo $1 '->' 'from folder:' $3 '-> to db:' $2
        else
            echo 'folder not found : ' $3
            exit;
        fi
    fi
}
function checkout_table {
    if [ -z "$3" ]; then
        echo 'specify table:';
        echo '    '$cmd $1 DATABASE TABLE;
        echo;
        exit;
    fi
}

function not_recognized {
    echo Command \`$1\` does not recognized;
    avaliable;
}

function checkout_specified_database {
    return 2;
}

# echo '$0:' $0; echo '$1:' $1; echo '$2:' $2; echo '$3:' $3; echo '$4:' $4;

# exit
