#!/bin/bash

# ==========================
# Import functions
source `which mysql_d3_librc`

avaliable_commands_list='run'

checkout_command $@
show_help $1

if test $1 == 'run'; then
    $cmd_mysql;
    exit;
fi

not_recognized $1
