#!/bin/bash

cmd=`basename $0`

# cmd pseudo-aliases cause of environment alias incapacity
if [ -z $mysql_group_suffix ]; then
    # echo could not extend mysqldump :  \$mysql_group_suffix is null;
    cmd_mysql="mysql";
    cmd_import="mysql";
    # --skip-quote-names ?
    cmd_dump="mysqldump --compact";
else
    cmd_mysql="mysql --defaults-group-suffix=$mysql_group_suffix";
    cmd_import="mysql --defaults-group-suffix=$mysql_group_suffix";
    cmd_dump="mysqldump --defaults-group-suffix=$mysql_group_suffix --compact";
    # mysqldump flags
    # --skip-opt
    # --compact
fi

function mysql_lambdaquery_read {
    $cmd_mysql -D $1 -e "$2;" | sed '1d';
}
function mysql_lambdaquery_showtables {
    $cmd_mysql -D $1 -e "SHOW TABLES;" | sed '1d';
}
function mysql_lambdaquery_write {
    $cmd_mysql -D $1 -e "SET foreign_key_checks=0; $2;" | sed '1d';
}
function mysql_import {
    # $1 - db name
    # $2 - $sqlfile
    if [ -f $sqlfile ]; then
        echo injecting $sqlfile ...;
        # disabled cause of foreign key order
        # $cmd_import -D $2 < $sqlfile;
        $cmd_import -D $1 -e "SET foreign_key_checks=0; source $2;";
    else
        echo error: $sqlfile not found;
    fi
}
function to_mysqldb_query {
    $cmd_mysql -D 'mysql' -e "$1";
}

function mysql_dump_headers {
    # mysql_dump_headers START
    # /*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
    # /*!40103 SET TIME_ZONE='+00:00' */;
    # /*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
    # /*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
    # /*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
    # mysql_dump_headers BODY
    # /*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
    # /*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
    # /*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
    # /*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;
    # mysql_dump_headers EOF
    return;
}


function avaliable {
    echo "Avaliable commands : $avaliable_commands_list";
    echo;
}
function show_help {
    if [ "$1" == 'help' ]; then
        usage;
        exit;
    fi
}

function checkout_connection {
    $cmd_mysql -e '\c';
    connection_code=$?;
    # if [ $? -eq 0 ]; then
        # connection_code=0;
    # else
        # connection_code=2;
    # fi
    if [ -z "$1" ]; then
        # silent mode
        if [ $connection_code -ne 0 ]; then
            exit;
        fi
    else
        # print mode
        if test $1 == 'out'; then
            if [ $connection_code -ne 0 ]; then
                # echo "no connection to DB:" $2;
                echo 'Connection : Fails';
            else
                echo 'Connection : OK';
            fi
            return;
        else
            echo 'unknown cmd';
        fi
        exit;
    fi
    # connection_code=$?;
}

function checkout_command {
    if [ -z "$1" ]; then
        avaliable;
        exit;
    fi
}
function checkout_database {
    if [ -z "$2" ]; then
        echo 'specify database:';
        echo '    '$cmd $1 DATABASE;
        echo;
        exit;
    fi
}
function checkout_name {
    if [ -z "$2" ]; then
        echo 'specify name:';
        echo '    '$cmd $1 NAME;
        echo;
        exit;
    fi
}
function checkout_folder {
    if [ -z "$3" ]; then
        echo 'specify folder:';
        echo '    '$cmd $1 $2 FOLDER;
        echo;
        exit;
    else
        if [ -d $3 ]; then
            echo $1 '->' 'from folder:' $3 '-> to db:' $2
        else
            echo 'folder not found : ' $3
            exit;
        fi
    fi
}
function checkout_table {
    if [ -z "$3" ]; then
        echo 'specify table:';
        echo '    '$cmd $1 DATABASE TABLE;
        echo;
        exit;
    fi
}

function not_recognized {
    echo Command \`$1\` does not recognized;
    avaliable;
}

function checkout_specified_database {
    return 2;
}

# echo '$0:' $0; echo '$1:' $1; echo '$2:' $2; echo '$3:' $3; echo '$4:' $4;

# exit
