#!/bin/bash

cmd=`basename $0`

# cmd pseudo-aliases cause of environment alias incapacity
if [ -z $mysql_group_suffix ]; then
    # echo could not extend mysqldump :  \$mysql_group_suffix is null;
    cmd_mysql="mysql";
    cmd_dump="mysqldump --compact";
else
    cmd_mysql="mysql --defaults-group-suffix=$mysql_group_suffix";
    cmd_dump="mysqldump --defaults-group-suffix=$mysql_group_suffix --compact";
fi

function mysql_lambda_query {
    $cmd_mysql -D $1 -e "$2;" | sed '1d';
}

function avaliable {
    echo "Avaliable commands : $avaliable_commands_list";
    echo;
}

function checkout_command {
    if [ -z "$1" ]; then
        avaliable;
        exit;
    fi
}
function checkout_database {
    if [ -z "$2" ]; then
        echo 'specify database:';
        echo '    '$cmd $1 DATABASE;
        echo;
        exit;
    fi
}
function checkout_table {
    if [ -z "$3" ]; then
        echo 'specify table:';
        echo '    '$cmd $1 DATABASE TABLE;
        echo;
        exit;
    fi
}

function not_recognized {
    echo Command \`$1\` does not recognized
    avaliable;
}

function checkout_specified_database {
    return 2;
}
# exit
