#!/bin/bash

# ==========================
# Import functions
source `which mysql_d3_librc`

avaliable_commands_list='help structure db check credentials'

function usage {
    echo;
    echo 'Sugar mysql & mysqldump tool';
    echo;
    echo usage:;
    echo '    '$cmd help;
    echo '    '$cmd info\|next DATABASE;
    echo example:;
    echo '    '$cmd info wpb_schema;
    echo;
}

checkout_command $@
show_help $1

if test $1 == 'check'; then
    checkout_connection out;
    exit;
fi

if test $1 == 'credentials'; then
    to_mysqldb_query "SELECT Host,User,Password FROM user";
    to_mysqldb_query "SELECT Host,Db,User FROM db";
    to_mysqldb_query "SELECT * FROM servers";
    to_mysqldb_query "SELECT Host,Db FROM host";
    to_mysqldb_query "SELECT Host,Db,User,Table_name FROM tables_priv";
    exit;
fi

if test $1 == 'db'; then
    # echo mysql -D $2 -e "SHOW TABLES;";
    # echo $cmd_mysql ;
    # echo q;
    exit;
fi

if test $1 == 'structure'; then
    checkout_database $@
    checkout_connection;
    COLUMNS_QUERY='SELECT count(COLUMN_NAME) FROM INFORMATION_SCHEMA.COLUMNS WHERE table_name =';
    TABLE_QUERY='SELECT count(*) FROM';
    for TABLE in $( mysql_lambda_query $2 "SHOW TABLES" ); do
        echo $TABLE "("\
        $(mysql_lambda_query $2 "$COLUMNS_QUERY '$TABLE'")\
        ") : "\
        $(mysql_lambda_query $2 "$TABLE_QUERY $TABLE") ;
    done
    exit;
fi

not_recognized $1
