#!/bin/bash

# SET
# export mysql_group_suffix='your ~/.my.cnf suffix'
# eval `mysql_d3suffix_set`
if [ -z $mysql_group_suffix ]; then
    echo echo \$mysql_group_suffix has not been exported to your environment
    echo echo usage:
    echo echo export mysql_group_suffix='yourdatabasesuffix'
else
    echo echo \\\$mysql_group_suffix now is : \$mysql_group_suffix \;
    echo SUFFIX=\"--defaults-group-suffix=\$mysql_group_suffix\" \;
    echo echo \\\$SUFFIX : \$SUFFIX \;
    echo alias mysql=\"mysql \$SUFFIX\" \;
    echo alias mysqldump=\"mysqldump \$SUFFIX\" \;
fi

# UNSET
echo unset mysql_group_suffix
echo unalias mysql
echo unalias mysqldump
echo echo cleared