#!/bin/bash

if [ -z "$1" ]; then 
    echo usage: $0 DATABASE TABLE; exit;
fi
if [ -z "$2" ]; then 
    echo usage: $0 DATABASE TABLE; exit;
fi

mysqldump --compact --no-data $1 $2 > $1__$2--schema.sql