#!/bin/bash

-- mysql -D $1 -e "SHOW TABLES;" | sed '1d'
function query { mysql -D mysql -e "$1"; }
 
query "SELECT Host,User,Password FROM user"
query "SELECT Host,Db,User FROM db"
query "SELECT * FROM servers"
query "SELECT Host,Db FROM host"
query "SELECT Host,Db,User,Table_name FROM tables_priv"
