#!/bin/bash

cmd=mysql
database=mysql
function query { $cmd -D $database -e "$1"; }
 
query "SELECT Host,User,Password FROM user"
query "SELECT Host,Db,User FROM db"
query "SELECT * FROM servers"
query "SELECT Host,Db FROM host"
query "SELECT Host,Db,User,Table_name FROM tables_priv"
