#!/bin/bash

# echo 0: $0; echo 1: $1; echo 2: $2; echo 3: $3;
cmd=`basename $0`

# ==========================
# Import functions : [ checkout_database , ]
source `which mysql_d3_librc`
# exit
# ==========================

avaliable_commands_list='help data schema solid all'
function usage {
    echo ''
    echo 'Export data to database__table--type.sql file , wo output'
    echo ''
    echo usage:
    echo '    '$cmd help;
    echo '    '$cmd all\|solid DATABASE;
    echo '    '$cmd data\|schema DATABASE [TABLE];
    echo example:
    echo '    '$cmd data mysql Users
    echo '    '$cmd schema mysql Users
    echo '    '$cmd all wpb
    echo
}

checkout_command $@

# cmd pseudo-aliases cause of environment alias incapacity
if [ -z $mysql_group_suffix ]; then
    # echo could not extend mysqldump :  \$mysql_group_suffix is null;
    cmd_dump="mysqldump --compact";
else
    cmd_dump="mysqldump --defaults-group-suffix=$mysql_group_suffix --compact";
fi

if test $1 == 'help'; then
    usage;
    exit;
fi

if test $1 == 'solid'; then
    checkout_database $@
    file=$2--solid.sql
    $cmd_dump --result-file=$file $2
    echo created: $file
    exit;
fi

if test $1 == 'all'; then
    checkout_database $@

    # checkout_specified_database $2
    dumpcontainer='mysqldump_'$2
    if [ ! -d $dumpcontainer ]; then
        mkdir $dumpcontainer
    fi
    exit;
    folder=`date '+%Y%m%d-%H%M%S'`
    mkdir $dumpcontainer/$folder

    cd $dumpcontainer/$folder

    for i in $( mysql -D $2 -e "SHOW TABLES;" | sed '1d' ); do
        echo "table: " $i
        mysql_d3dump_schema $2 $i
        mysql_d3dump_data $2 $i
    done

    mysql_d3dump_solid $2
    cd ../..

    exit;
fi

if test $1 == 'data'; then
    # mysqldump --compact --no-create-info --skip-extended-insert --result-file=DB__TABLE--data.sql DB TABLE
    checkout_database $@
    checkout_table $@
    arguments='--no-create-info --skip-extended-insert'
    file=$2__$3--data.sql
    $cmd_dump $arguments --result-file=$file $2 $3
    exit;
fi

if test $1 == 'schema'; then
    checkout_database $@
    checkout_table $@
    arguments='--no-data'
    file=$2__$3--schema.sql
    echo
    alias -p
    echo
    echo $cmd_dump $arguments --result-file=$file $2 $3
    $cmd_dump $arguments $2 $3
    echo
    exit;
fi

echo Command \`$1\` does not recognized
avaliable;
