#!/bin/bash

# ==========================
# Import functions
source `which mysql_d3_librc`

avaliable_commands_list='help data schema solid all'
function usage {
    echo ''
    echo 'Export data to database__table--type.sql file , wo output'
    echo ''
    echo usage:
    echo '    '$cmd help;
    echo '    '$cmd all\|solid DATABASE;
    echo '    '$cmd data\|schema DATABASE [TABLE];
    echo example:
    echo '    '$cmd data mysql Users
    echo '    '$cmd schema mysql Users
    echo '    '$cmd all wpb
    echo
}

checkout_command $@
show_help $1

if test $1 == 'solid'; then
    checkout_database $@
    file=$2--solid.sql
    $cmd_dump --result-file=$file $2
    echo created: $file
    exit;
fi

if test $1 == 'all'; then
    checkout_database $@

    # checkout_specified_database $2
    dumpcontainer='mysqldump_'$2
    if [ ! -d $dumpcontainer ]; then
        mkdir $dumpcontainer
    fi
    folder=`date '+%Y%m%d-%H%M%S'`
    mkdir $dumpcontainer/$folder
    cd $dumpcontainer/$folder

    for i in $( mysql_lambdaquery_showtables $2 ); do
        echo "table: " $i
        mysql_d3dump schema $2 $i
        mysql_d3dump data $2 $i
    done

    if [ `which column` ]; then
        mysql_d3info structure $2 | column -t > structure.txt;
    else
        mysql_d3info structure $2 > structure.txt;
        # @TODO: column analog
    fi

    # mysql_d3dump solid $2
    cd ../..

    exit;
fi

if test $1 == 'data'; then
    # mysqldump --compact --no-create-info --skip-extended-insert --result-file=DB__TABLE--data.sql DB TABLE
    checkout_database $@
    checkout_table $@
    arguments='--no-create-info --skip-extended-insert'
    file=$2__$3--data.sql
    $cmd_dump $arguments --result-file=$file $2 $3
    exit;
fi

if test $1 == 'schema'; then
    checkout_database $@
    checkout_table $@
    arguments='--no-data'
    file=$2__$3--schema.sql
    $cmd_dump $arguments --result-file=$file $2 $3
    exit;
fi

not_recognized $1
