#!/bin/bash

cmd=`basename $0`
# ==========================
# Import functions : [ checkout_database , ]
source `which mysql_d3_librc`
# exit
# ==========================

avaliable_commands_list='help info check'

function usage {
    echo;
    echo 'Sugar mysql & mysqldump tool';
    echo;
    echo usage:;
    echo '    '$cmd help;
    echo '    '$cmd info\|next DATABASE;
    echo example:;
    echo '    '$cmd into wpb;
    echo;
}

checkout_command $@

if [ -z $mysql_group_suffix ]; then
    # echo could not extend mysqldump :  \$mysql_group_suffix is null;
    cmd_mysql="mysql";
else
    cmd_mysql="mysql --defaults-group-suffix=$mysql_group_suffix";
fi

function connection_checkout {
    # $cmd_mysql -e '\c' 2> /dev/null;
    $cmd_mysql -e '\c';
    if [ $? -eq 0 ]; then
        echo 'Connection : OK'
        return 0;
    else
        echo 'Connection : Fails'
        return 2;
    fi
}

if test $1 == 'help'; then
    usage;
    exit;
fi

if test $1 == 'check'; then
    connection_checkout;
    exit;
fi

if test $1 == 'credentials'; then
    function query { $cmd_mysql -D database=mysql -e "$1"; };
    query "SELECT Host,User,Password FROM user";
    query "SELECT Host,Db,User FROM db";
    query "SELECT * FROM servers";
    query "SELECT Host,Db FROM host";
    query "SELECT Host,Db,User,Table_name FROM tables_priv";
    exit;
fi

if test $1 == 'db'; then
    # echo mysql -D $2 -e "SHOW TABLES;";
    # echo $cmd_mysql ;
    # echo q;
    exit;
fi

if test $1 == 'info'; then
    checkout_database $@
    COLUMNS_QUERY='SELECT count(COLUMN_NAME) FROM INFORMATION_SCHEMA.COLUMNS WHERE table_name =';
    TABLE_QUERY='SELECT count(*) FROM';
    function query { $cmd_mysql -D $1 -e "$2;" | sed '1d'; }
    connection_checkout;
    connection_code=$?;
    if [ $connection_code -ne 0 ]; then
        echo "no connection to DB:" $2;
        exit;
    fi
    for TABLE in $( query $2 "SHOW TABLES" ); do
        echo $TABLE "("\
        $(query $2 "$COLUMNS_QUERY '$TABLE'")\
        ") : "\
        $(query $2 "$TABLE_QUERY $TABLE") ;
    done
    exit;
fi

echo Command \`$1\` does not recognized
avaliable;
